# Generated by Django 5.1.4 on 2025-01-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBaseInfoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CreateContractInfoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_wages', models.CharField(max_length=30)),
                ('hours_per_week', models.CharField(max_length=30)),
                ('official_position', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnboardingWebsite.createbaseinforecord')),
            ],
        ),
        migrations.CreateModel(
            name='CreateOnboardingInfoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_and_safety', models.CharField(max_length=30)),
                ('fire_drill', models.CharField(max_length=30)),
                ('kpi_creation', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnboardingWebsite.createbaseinforecord')),
            ],
        ),
    ]
